### ISSUE TITLE
Select different source files for application configs

### ISSUE THREAD

**Issue by danielpieczko** [xmos/xcommon_cmake#125]
Application configs can just select different compiler options. This is a request to be able to select different sets of sources for each config, for example:
```
set(APP_C_SRCS src/main.c)
set(APP_C_SRCS_cfg0 src/config0.c)   # App config cfg0 would build main.c and config0.c, not config1.c
set(APP_C_SRCS_cfg1 src/config1.c)   # App config cfg1 would build main.c and config1.c, not config0.c
```

xcommon would compile the unwanted files in every config, eg. when building a non-SPDIF config of USB Audio, the lib_spdif sources get built.

**Comment by xross** [comment]
This is missing functionality from the original xcommon and should be included. 

See:
SOURCE_FILES_[binary] which sets source files specific to a particular binary

It wouldn't help the the specific lib_spdif example though.

**Comment by xross** [comment]
Agreed, I don't think we should look to address the latter issue - it would require listing deps in multple places and it might get messy. 

BTW a sort of workaround of this missing feature could be to use the CONFIG define in the source code, however, since its a string it not really that useful.. maybe that define should be -DCONFIG_<config> rather than -DCONFIG=<config>
